### ISSUE TITLE
[Enhancement]: Responsive Design

### ISSUE THREAD

**Issue by evenstensberg** [rishabh3112/webpack-ui#2]
Right now the UI is not having enough responsiveness in its design. It would be great to have the styles respect each others boundaries

**Comment by rishabh3112** [comment]
Thanks for feedback ❤
I have a point to make. As this is a local tool, one have to have access to terminal for getting this tool running thus I suppose mobile devices are out of the use case as they don't. And it is currently made it responsive enough for a tablet size.

If you faced problem in a screen size you felt should not, please share screen dimensions and that should be a easy fix.

**Comment by evenstensberg** [comment]
Yes. What I mean by responsive is that we will need to make the design not look that noisy. Currently a lot of the blocks are all around the place with no boundary.

**Comment by rishabh3112** [comment]
Ohh, as far as design of pages is meant, I am currently focusing on new features and at UI a loosy implementation of material design, just focusing on that it is just useful for testing features.

Would be great if you can share some examples and I will try to mend them ASAP 👍

**Comment by evenstensberg** [comment]
The landing page, for instance, would need some mc luvin

**Comment by rishabh3112** [comment]
Okay, will do when free. Currently busy working on [`webpack-ui/webpack-ui`](https://github.com/webpack-ui/webpack-ui) and some of my own stuff :)
