### ISSUE TITLE
material-ui icon filenames have wrong case

### ISSUE THREAD

**Issue by thraidh** [rishabh3112/webpack-ui#3]
When trying to run on Linux I get errors like this:
```
ERROR in ./src/components/StatusBar.js
Module not found: Error: Can't resolve '@material-ui/icons/warning' in '/home/.../git/webpack-ui/src/client/src/components'
```
This is due to the fact that the file is actually called `@material-ui/icons/Warning.js` with a capital W. There are more errors like this. `case-sensitive-paths-webpack-plugin` is a good way to avoid this situation.

**Comment by rishabh3112** [comment]
Thanks for pointing out!
I don't want to increase my development dependencies, instead will take care of it while reviewing commits and PRs in future.
